### ISSUE TITLE
Error Event Exception!

### ISSUE THREAD

**Issue by Piesrgr8** [Piesrgr8/Battlecraft-Server-1.9#1]
Error passing an event for when a player sends a message.

Error in Console:
[22:11:59 ERROR]: Could not pass event AsyncPlayerChatEvent to BattlecraftServer v1.5, 1.9
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot194.jar:git-Spigot-798f32d-0cd0397]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot194.jar:git-Spigot-798f32d-0cd0397]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot194.jar:git-Spigot-798f32d-0cd0397]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [spigot194.jar:git-Spigot-798f32d-0cd0397]
        at net.minecraft.server.v1_9_R2.PlayerConnection.chat(PlayerConnection.java:1271) [spigot194.jar:git-Spigot-798f32d-0cd0397]
        at net.minecraft.server.v1_9_R2.PlayerConnection.a(PlayerConnection.java:1209) [spigot194.jar:git-Spigot-798f32d-0cd0397]
        at net.minecraft.server.v1_9_R2.PacketPlayInChat$1.run(PacketPlayInChat.java:39) [spigot194.jar:git-Spigot-798f32d-0cd0397]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_101]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_101]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_101]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_101]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_101]
Caused by: java.util.UnknownFormatConversionException: Conversion = ' '
        at org.bukkit.event.player.AsyncPlayerChatEvent.setFormat(AsyncPlayerChatEvent.java:100) ~[spigot194.jar:git-Spigot-798f32d-0cd0397]
        at org.battlecraft.piesrgr8.essentials.Chat.chat(Chat.java:30) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_101]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_101]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_101]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_101]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot194.jar:git-Spigot-798f32d-0cd0397]
        ... 11 more

**Comment by iHersh** [comment]
need to see the rest of the error this doesn't tell me anything
